# Generated by Django 5.0.1 on 2024-01-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_alter_topthreetip_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='round',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
